/*
 * rokka.io
 * digital image processing done right. [Documentation](https://rokka.io/documentation). [Changelog](https://api.rokka.io/changelog.md).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.rokka.client.codegen.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OrganizationDefinition
 */

public class OrganizationDefinition {
  @SerializedName("billing_email")
  private String billingEmail = null;

  @SerializedName("display_name")
  private String displayName = null;

  @SerializedName("master_organization")
  private String masterOrganization = null;

  public OrganizationDefinition billingEmail(String billingEmail) {
    this.billingEmail = billingEmail;
    return this;
  }

   /**
   * Get billingEmail
   * @return billingEmail
  **/
  @ApiModelProperty(required = true, value = "")
  public String getBillingEmail() {
    return billingEmail;
  }

  public void setBillingEmail(String billingEmail) {
    this.billingEmail = billingEmail;
  }

  public OrganizationDefinition displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @ApiModelProperty(value = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public OrganizationDefinition masterOrganization(String masterOrganization) {
    this.masterOrganization = masterOrganization;
    return this;
  }

   /**
   * Get masterOrganization
   * @return masterOrganization
  **/
  @ApiModelProperty(value = "")
  public String getMasterOrganization() {
    return masterOrganization;
  }

  public void setMasterOrganization(String masterOrganization) {
    this.masterOrganization = masterOrganization;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizationDefinition organizationDefinition = (OrganizationDefinition) o;
    return Objects.equals(this.billingEmail, organizationDefinition.billingEmail) &&
        Objects.equals(this.displayName, organizationDefinition.displayName) &&
        Objects.equals(this.masterOrganization, organizationDefinition.masterOrganization);
  }

  @Override
  public int hashCode() {
    return Objects.hash(billingEmail, displayName, masterOrganization);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganizationDefinition {\n");
    
    sb.append("    billingEmail: ").append(toIndentedString(billingEmail)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    masterOrganization: ").append(toIndentedString(masterOrganization)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

