/*
 * rokka.io
 * digital image processing done right. [Documentation](https://rokka.io/documentation). [Changelog](https://api.rokka.io/changelog.md).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.rokka.client.codegen.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.rokka.client.codegen.model.StackExpression;
import io.rokka.client.codegen.model.StackOperation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * Stack
 */

public class Stack {
  @SerializedName("name")
  private String name = null;

  @SerializedName("organization")
  private String organization = null;

  @SerializedName("created")
  private OffsetDateTime created = null;

  @SerializedName("stack_operations")
  private List<StackOperation> stackOperations = null;

  @SerializedName("stack_options")
  private Object stackOptions = null;

  @SerializedName("stack_expressions")
  private List<StackExpression> stackExpressions = null;

  @SerializedName("link")
  private String link = null;

  public Stack name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "your-stack-name", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Stack organization(String organization) {
    this.organization = organization;
    return this;
  }

   /**
   * Get organization
   * @return organization
  **/
  @ApiModelProperty(example = "your-organization", value = "")
  public String getOrganization() {
    return organization;
  }

  public void setOrganization(String organization) {
    this.organization = organization;
  }

  public Stack created(OffsetDateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }

  public Stack stackOperations(List<StackOperation> stackOperations) {
    this.stackOperations = stackOperations;
    return this;
  }

  public Stack addStackOperationsItem(StackOperation stackOperationsItem) {
    if (this.stackOperations == null) {
      this.stackOperations = new ArrayList<StackOperation>();
    }
    this.stackOperations.add(stackOperationsItem);
    return this;
  }

   /**
   * Get stackOperations
   * @return stackOperations
  **/
  @ApiModelProperty(value = "")
  public List<StackOperation> getStackOperations() {
    return stackOperations;
  }

  public void setStackOperations(List<StackOperation> stackOperations) {
    this.stackOperations = stackOperations;
  }

  public Stack stackOptions(Object stackOptions) {
    this.stackOptions = stackOptions;
    return this;
  }

   /**
   * Get stackOptions
   * @return stackOptions
  **/
  @ApiModelProperty(example = "", value = "")
  public Object getStackOptions() {
    return stackOptions;
  }

  public void setStackOptions(Object stackOptions) {
    this.stackOptions = stackOptions;
  }

  public Stack stackExpressions(List<StackExpression> stackExpressions) {
    this.stackExpressions = stackExpressions;
    return this;
  }

  public Stack addStackExpressionsItem(StackExpression stackExpressionsItem) {
    if (this.stackExpressions == null) {
      this.stackExpressions = new ArrayList<StackExpression>();
    }
    this.stackExpressions.add(stackExpressionsItem);
    return this;
  }

   /**
   * Get stackExpressions
   * @return stackExpressions
  **/
  @ApiModelProperty(value = "")
  public List<StackExpression> getStackExpressions() {
    return stackExpressions;
  }

  public void setStackExpressions(List<StackExpression> stackExpressions) {
    this.stackExpressions = stackExpressions;
  }

  public Stack link(String link) {
    this.link = link;
    return this;
  }

   /**
   * Get link
   * @return link
  **/
  @ApiModelProperty(example = "/stacks/your-organization/your-stack-name", value = "")
  public String getLink() {
    return link;
  }

  public void setLink(String link) {
    this.link = link;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Stack stack = (Stack) o;
    return Objects.equals(this.name, stack.name) &&
        Objects.equals(this.organization, stack.organization) &&
        Objects.equals(this.created, stack.created) &&
        Objects.equals(this.stackOperations, stack.stackOperations) &&
        Objects.equals(this.stackOptions, stack.stackOptions) &&
        Objects.equals(this.stackExpressions, stack.stackExpressions) &&
        Objects.equals(this.link, stack.link);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, organization, created, stackOperations, stackOptions, stackExpressions, link);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Stack {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    stackOperations: ").append(toIndentedString(stackOperations)).append("\n");
    sb.append("    stackOptions: ").append(toIndentedString(stackOptions)).append("\n");
    sb.append("    stackExpressions: ").append(toIndentedString(stackExpressions)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

