/*
 * rokka.io
 * digital image processing done right. [Documentation](https://rokka.io/documentation). [Changelog](https://api.rokka.io/changelog.md).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.rokka.client.codegen.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * UserDefinition
 */

public class UserDefinition {
  @SerializedName("email")
  private String email = null;

  @SerializedName("organization")
  private String organization = null;

  public UserDefinition email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Unique email for the new user
   * @return email
  **/
  @ApiModelProperty(example = "someone@example.org", required = true, value = "Unique email for the new user")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public UserDefinition organization(String organization) {
    this.organization = organization;
    return this;
  }

   /**
   * If set, a new organization with that name will be created
   * @return organization
  **/
  @ApiModelProperty(example = "yourneworganization", value = "If set, a new organization with that name will be created")
  public String getOrganization() {
    return organization;
  }

  public void setOrganization(String organization) {
    this.organization = organization;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserDefinition userDefinition = (UserDefinition) o;
    return Objects.equals(this.email, userDefinition.email) &&
        Objects.equals(this.organization, userDefinition.organization);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, organization);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserDefinition {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

